---

- hosts: all
  become: true
  tasks:
  
  - name: install webserver and php package
    package: 
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

  - name: Start httpd service
    ansible.builtin.systemd_service:
     state: started
     name: httpd 

  - name: open port 80 cent-os
    ansible.posix.firewalld:
      port: 80/tcp
      permanent: true
      state: enabled
