---

- hosts: all
  become: true
  tasks:
  
  - name: install apache2 webserver and php package
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 webserver and php package
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Start httpd service
    ansible.builtin.systemd_service:
     state: started
     name: httpd 

  - name: open port 80 cent-os
    ansible.posix.firewalld:
      port: 80/tcp
      permanent: true
      state: enabled
